### ISSUE TITLE
Undefined variable: new_url

### ISSUE THREAD

**Issue by froschdesign** [robphilp/Symphony-2-Router#7]
During my last test following error occurred:

> Undefined variable: new_url
> An error occurred in /extensions/router/extension.driver.php around line 190

Fix:

``` php
public function frontendPrePageResolve($context)
{
    $routes  = $this->getRoutes();
    $url     = $context['page'];
    $new_url = null;

    foreach($routes as $route) {
        if(preg_match($route['from'], $url, $matches) == 1) {
            $new_url = preg_replace($route['from'], $route['to'], $url);

            if(Symphony::Configuration()->get('redirect', 'router') == 'yes') {
                header("Location:" . $new_url);
                die();
            }
            break;
        }
    }

    if(null !== $new_url) {
        $context['page'] = $new_url;
    }
}
```

Thanks!

**Comment by nitriques** [comment]
looks like this repro is not maintain anymore.... we should start a new one don't you think ? I have a lot of little fix/improvement to be made in this ext... take a look a nickdunn's fork https://github.com/robphilp/Symphony-2-Router/pull/6

He is the more advance I could find (via network graph)
